#!/bin/sh

set -e

bundle exec jekyll build
gem build jekyll-theme-cayman-blog.gemspec

rm -rf ../Gitnoter.github.io/zh
cp -rf _site ../Gitnoter.github.io/zh

cd ../Gitnoter.github.io/
git add .
git commit -a -m "$1"
git push origin master
